### ISSUE TITLE
Range inputs

### ISSUE THREAD

**Issue by gavinballard** [discolabs/grunt-shopify-theme-settings#18]
Would be nice to have a couple of new input types that dealt with ranges (specifically, time and date ranges) as they're a pretty common pattern. Something like:

``` yml
...
    Business Hours:
      name: business_hours
      type: range-hours
      start: 00:00
      stop: 23:00
      step: 00:30
```
